decide/authentication/serializers.py
decide/authentication/urls.py
decide/authentication/views.py

An endpoint has been created for the user registration that returns a JSON with the created user and its token. (Issue #23 )

FEAT: ENDPOINT REGISTER USER API

---

decide/postproc/admin.py
decide/postproc/models.py

Added gender attribute to user using a OneToOne relationship between UserProfile and User. (Issue #40  )

FEAT: ADDED GENRE TO USER

---

decide/authentication/urls.py
decide/authentication/views.py

An endpoint has been created for the user login that returns a JSON with the token and expired date. (Issue #44)

FEAT: ENDPOINT LOGIN USER API

---

.gitignore
decide/decide/settings.py
decide/decide/urls.py
requirements.txt

I've implemented the basic oauth configuration for allowing login/signup by using other apps.
Closes #51

FEAT: IMPLEMENTING OAUTH

---

decide/base/templates/base.html
decide/decide/urls.py

Se ha implementado en el base.html un select que permite cambiar el idioma de la página desde la interfaz de usuario.

FEAT: INTERFAZ TRADUCIBLE

---

decide/authentication/fixtures/initial_data.json
decide/decide/settings.py
decide/visualizer/templates/signin.html

The alternative login using the LinkedIn social account has been implemented

FEAT: LINKEDIN LOGIN ADDED

---

decide/booth/templates/booth/booth.html
decide/visualizer/templates/visualizer/visualizer.html

Now HTML has comments to indicate where translations are needed

FEAT: Adapted the HTML

---

decide/authentication/tests.py
decide/base/templates/base.html

I have created some selenium tests that check the functionality of traductions in the signing view

FEAT: SELENIUM TEST FOR SIGNING PAGE TRASLATION ADDED

---

decide/authentication/form.py
decide/authentication/tests.py
decide/authentication/urls.py
decide/authentication/views.py
decide/visualizer/templates/hello.html
decide/visualizer/templates/profile.html

IMPLEMENTATION OF USER EDITING AND DELETING FUNCTIONALITIES

FEAT: EDIT AND DELETE USER FUNCIONALITIY

---

decide/authentication/fixtures/initial_data.json
decide/decide/settings.py
decide/visualizer/templates/signin.html

The alternative login using the AUTH0 social account has been implemented

AUTH0 LOGIN ADDED

---

decide/authentication/fixtures/initial_data.json
decide/decide/settings.py
decide/visualizer/templates/signin.html

The alternative login using the Facebook social account has been implemented

FEAT: FACEBOOK LOGIN ADDED

---

decide/postproc/views.py
decide/voting/models.py

Made the algorythm less computationally demanding

REFACTOR: INCREASE EFFICIENCY OF D'HONDT ALGORYTHM

---

decide/visualizer/templates/hello.html
decide/visualizer/templates/profile.html
decide/visualizer/templates/signin.html
decide/visualizer/templates/signup.html

Import of i18n added to the remaining templates, along with help for translation

REFACTOR: ADDED INSTRUCTIONS TO HELP TRANSLATION

---

decide/postproc/tests.py
decide/voting/tests.py

Tests for order votations done, coverage almost maximum

TEST: Test order votation

---

decide/dashboard/templates/dashboard_with_pv.html
decide/dashboard/views.py

Modified the dashboard template to add an identifier for translation module.

FEAT:Finished feature/141

---

.github/workflows/django.yml
.gitignore
decide/dashboard/templates/dashboard/dashboard.html

Added where to add translations so as decide-part-trebujena-1 group know what they should translate. In addition, corrected actions.

REFACTOR: Added where to add translations + actions

---

.gitignore
decide/base/static/base/style.css
decide/base/templates/mainpage.html
decide/base/views.py
decide/booth/templates/booth/booth.html
decide/decide/urls.py
decide/voting/templates/voting/list.html

Pendig review. Need to do some tests while trebujena-1 are making translations.

feat: main page with redirections if user is not logged

---

.github/workflows/django.yml
.github/workflows/release.yml
.gitignore

Necessary merge towards develop. Afterwards, everyone should update their modules.

feat: GitHub Actions Workflows for push+releases

---

decide/decide/settings.py

Added dashboard to decide/settings (modules)

Fix: Dashboard problems

---

decide/postproc/tests.py

The test suite for borda tets has been upgraded by 2 more tests

TEST: More model tests

---

decide/postproc/tests.py
decide/postproc/views.py

Also privatized some postproc methods

TEST: ADD POSITIVE UNIT TEST CASE FOR DHONDT ALGORYTHM

---

decide/voting/tests.py

Also added model test for dhondt question save method override

TEST: ADD MODEL TESTS FOR VOTING WITH DHONDT QUESTION

---

decide/postproc/tests.py
decide/postproc/views.py

Created ValueError trigger in the algorythm to manage these cases

TEST: ADD UNITARY NEGATIVE TEST CASES FOR DHONDT ALGORYTHM

---

decide/authentication/management/commands/init_superuser.py
docker/Dockerfile
docker/docker-compose.yml
docker/docker-settings.py

I've uploaded the new docker folder so the Selenium tests could be launched and the superuser is created. I've decided to let the Dockerfile ready for develop (it will need to be updated when the develop branch merges with main so that the docker image will be checked to be working properly in that branch and so the Docker will be build from main just before the release).
For testing the functionality you will need to change line 19 of the Dockerfile with "RUN git checkout feature/230" so that the  image would use this branch to build itself.
Closes #230

R-015 INCIDENCE - DOCKER

---

.github/workflows/django.yml
decide/local_settings.gactions.py

Dashboard was missing from MODULES and threw an error on makemigrations.

fix: Consider dashboard in actions settings

---

decide/authentication/tests.py

I've tested the register form
Closes #258

TEST: THE REGISTER VIEW HAS BEEN TESTED

---

decide/authentication/tests.py

TEST: NEW SELENIUM TEST FOR THE LOGIN FUNCIONLITY

---

decide/authentication/views.py
decide/census/tests.py
decide/census/views.py

From now on, it is necessary to be logged in to import and export the census excel. (Closes #188 )

FEAT: LOGIN REQUIRED IMPORT/EXPORT EXCEL

---

decide/authentication/templates/profile.html
decide/authentication/tests.py
decide/base/templates/mainpage.html
decide/base/views.py
decide/census/templates/census/census.html
decide/census/templates/census/census_details.html
decide/census/templates/census/census_reuse_form.html
decide/census/templates/census/export.html
decide/census/templates/census/import.html
decide/census/templates/csv.html
decide/census/templates/json.html
decide/census/tests.py
decide/census/views.py
decide/dashboard/templates/dashboard/dashboard.html

Tables and templates are responsive and more accessible.

FIX: Improve responsivity and fix tests

---

decide/census/forms.py

NOW IS SOLVED THE ERROR ON THE CENSUS FORMS

FIX: ERROR ON VAGRANT AND DOCKER SOLVED

---

decide/base/views.py

Creation of a token and a gender for users who log in with the social account

FIX:SOCIAL ACCOUNT USER TOKEN AND GENRE

---

vagrant/Vagrantfile
vagrant/django.yml
vagrant/files.yml
vagrant/files/vagrant_settings.py
vagrant/packages.yml
vagrant/playbook.yml
vagrant/python.yml

The vagrant deployment has been set up
Closes #269

FEAT: VAGRANT
